### ISSUE TITLE
Datenpunkt id hinzufügen 

### ISSUE THREAD

**Issue by tobkoh** [TKnpl/ioBroker.divera247#10]
Hallo, 

wäre es möglich noch den Datenpunkt id hinzuzufügen? 
Also die interne Divera Einsatz id .

Besten Dank

**Comment by TKnpl** [comment]
Hallo.
Das ist möglich. Darf ich den Einsatzzweck/Nutzen erfragen?
Viele Grüße

**Comment by TKnpl** [comment]
@tobkoh ich habe den Datenpunkte "divera_id" hinzugefügt.
Wenn du deine jetzige Adapter-Instanz löscht, dann über Github dir die aktuelle Version ziehst und dann eine neue Instanz hinzufügst, dann kommt der Datenpunkt hinzu.
