### ISSUE TITLE
API Key der normalen DIVERA User nutzen

### ISSUE THREAD

**Issue by lioncar2000** [TKnpl/ioBroker.divera247#13]
Halli hallo,

Cooler Adapter, danke dafür!!
Leider reagiert dieser aber "nur" auf die admin API des DIVERA Accounts. Den bekommt man als normaler Nutzer nur schlecht.

Kann der Alarm auch über Nutzer API genutzt werden?

Gruss
T Nitsche

**Comment by TKnpl** [comment]
Hallo,
in der neuen Version kann man sich mit seinem Benutzernamen und Passwort anmelden. Dieser ist jedoch noch nicht offiziell released. Wenn du ihn aber schon testen möchtest, kannst du am besten den Adapter bei dir stoppen, solltest du ihn schon aktiv am laufen haben, dann über Github die aktuelle Version installieren und anschließend wieder starten und im Admin-Bereich deine Daten eingeben.

**Comment by TKnpl** [comment]
will be implemented within the new version of this adapter.
