### ISSUE TITLE
Datenpunkt alarm aktualisiert nicht immer

### ISSUE THREAD

**Issue by TheZulu18** [TKnpl/ioBroker.divera247#18]
Der Datenpunkt alarm aktualisiert sich nicht. Nach einer Alarmierung stellt sich der Status auf true. Es kommt aber leider ab und zu vor, das dieser nicht wieder zeitnahe zurückspringt auf false, sobald der Alarm beendet ist.

**Comment by TKnpl** [comment]
Die Daten werden aus der Divera Schnittstelle übernommen. Erst wenn der Alarm in Divera als abgeschlossen gekennzeichnet wird, wird dieser Adapter das entsprechend übernehmen.
