### ISSUE TITLE
Alarm-Datenpunkt reagiert auf Rückmeldungen

### ISSUE THREAD

**Issue by lonisgree** [TKnpl/ioBroker.divera247#19]
Moin, als heute per Divera der Probealarm reingekommen ist, hat der Adapter auch ausgelöst. Als dann aber die Rückmeldungen zum Alarm kamen, wurde jedes mal der Alarm-Datenpunkt wieder auf "true" gesetzt. Habe ich irgendwas falsch gemacht oder woran könnte das liegen?

**Versions:**  
 - Adapter version: 0.2.0
 - JS-Controller version: 4.0.23
 - Node version: v12.22.12
 - Operating system: Raspberry Pi 4 Model B

**Comment by TKnpl** [comment]
Hallo, da es sich bei den Rückmeldungen um Updates des Alarms handelt, ist das Verhalten korrekt.
Sollten Scripte auf den Datenpunkten laufen bitte entsprechend die Logik anpassen.
Viele Grüße
