### ISSUE TITLE
Hinzufügen DIVERA-ID Nummer (id) und alarmierte Fahrzeuge (vehicle)

### ISSUE THREAD

**Issue by tobkoh** [TKnpl/ioBroker.divera247#4]
Hallo, 

könntest das Plugin noch um folgende Datenpunkte ergänzen id und vehicle ich habe das mal in meinem Fork versucht und es scheint stabil zu laufen.

Ich nutze in Iobroker ein Blockly-Script das den aktuellen Status der Fahrzeuge abfragt und den Einsatz schließt sobald die Fahrzeuge wieder im Status 2 sind. Funktioniert bisher ganz gut. 

Gruß Tobkoh

**Comment by TKnpl** [comment]
Added vehicle, id is just a technical id that should not be necessary
