### ISSUE TITLE
Aktualisierung der Einsatzdaten 

### ISSUE THREAD

**Issue by tobkoh** [TKnpl/ioBroker.divera247#5]
Hallo, 

wenn ein Einsatz läuft und z.B. von was hinzugefügt oder geändert wir innerhalb des offenen Einsatz dann wird dies nicht erkannt. Besonders ist es mir aufgefallen wenn weitere Gruppen innerhalb einer Einheit alarmiert werden. 

Ist jedoch bei allen Daten Punkten so. 

Wird jedoch ein neuer Einsatz auf gemacht, dann wird dieser vom Plugin erkannt.

**Comment by TKnpl** [comment]
I have to check the possibilities to realise that

**Comment by TKnpl** [comment]
There is a new API version published from divera247 that makes this request much more easy to implement.
I'll add it now to my backlog.

**Comment by TKnpl** [comment]
Hi @tobkoh ,
i've included the updates to this adapter. If you want to use it right now, please install the latest version in your ioBroker by installing via. Github.
Next beta release of this adapter will follow soon.
Have fun with it :-)

**Comment by TKnpl** [comment]
done
